name: getx_apk
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/images/logo.png
  - assets/images/product1.png
  - assets/images/product2.png
  - assets/images/product3.png
  - assets/images/product4.png
  - assets/images/product5.png
  - assets/images/product6.png
  - assets/images/OBJECTS.png

  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Medium
      fonts: 
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Bold
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins Extra Bold
      fonts: 
        - asset: assets/fonts/Poppins-ExtraBold.ttf

